// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PromotionService is an autogenerated mock type for the PromotionService type
type PromotionService struct {
	mock.Mock
}

// CalculateDiscount provides a mock function with given fields: amount
func (_m *PromotionService) CalculateDiscount(amount int) (int, error) {
	ret := _m.Called(amount)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPromotionService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPromotionService creates a new instance of PromotionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPromotionService(t mockConstructorTestingTNewPromotionService) *PromotionService {
	mock := &PromotionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
