// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	repositories "github.com/pradist/promotion/repositories"
	mock "github.com/stretchr/testify/mock"
)

// PromotionRepository is an autogenerated mock type for the PromotionRepository type
type PromotionRepository struct {
	mock.Mock
}

// GetPromotion provides a mock function with given fields:
func (_m *PromotionRepository) GetPromotion() (repositories.Promotion, error) {
	ret := _m.Called()

	var r0 repositories.Promotion
	if rf, ok := ret.Get(0).(func() repositories.Promotion); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(repositories.Promotion)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPromotionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPromotionRepository creates a new instance of PromotionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPromotionRepository(t mockConstructorTestingTNewPromotionRepository) *PromotionRepository {
	mock := &PromotionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
